package com.SmartCampus.SmartCampus.Entity.enums;

public enum NotificationType {
    TICKET_CREATED,
    TICKET_ASSIGNED,
    TICKET_STATUS_UPDATED,
    RESOLUTION_NOTE_ADDED,
    TICKET_RESOLVED,
    BOOKING_CREATED,
    BOOKING_APPROVED,
    BOOKING_CANCELLED,
    BOOKING_REJECTED,
    RESOURCE_CREATED,
    RESOURCE_UPDATED,
    RESOURCE_DELETED
}
