spring.application.name=SmartCampus
spring.mongodb.uri=mongodb://localhost:27017/smartcampus_db
spring.mongodb.database=smartcampus_db
server.port=8080
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=15MB
file.upload-dir=./uploads/
spring.profiles.active=dev
logging.level.com.smartcampus=INFO
logging.level.org.springframework.data.mongodb=WARN
app.admin.seed.enabled=true
app.admin.full-name=Smart Campus Admin
app.admin.email=admin@smartcampus.com
app.admin.password=Admin@123
